pipeline {

    agent {
        docker {
            image 'jibin321/maven-docker-agent:v2'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    stages {

        stage('Checkout') {
            steps {
                sh 'echo passed'
                //git branch: 'main', url: 'https://github.com/user/repo.git'
            }
        }

        stage('Build and Test') {
            steps {
                sh 'ls -ltr'

                // build the project and create a JAR file
                sh 'cd spring-boot-app && mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {
                    sh '''
                        cd spring-boot-app
                        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:5.1.0.4751:sonar \
                        -Dsonar.projectKey=my-ec2-project \
                        -Dsonar.projectName="Spring Boot App" \
                        -Dsonar.host.url=$SONAR_HOST_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {

            environment {
                DOCKER_IMAGE = "afthab12/spring-boot-app:${BUILD_NUMBER}"
                REGISTRY_CREDENTIALS = credentials('docker-cred')
            }

            steps {
                script {
                    sh 'cd spring-boot-app && docker build -t ${DOCKER_IMAGE} .'

                    def dockerImage = docker.image("${DOCKER_IMAGE}")

                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                        dockerImage.push()
                        dockerImage.push("latest")
                    }
                }
            }
        }

stage('Update Deployment File') {

    environment {
        GIT_REPO_NAME = "java-mavn-sonarqube-argocd"
        GIT_USER_NAME = "Afthabahammed"
    }

    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'github',
                usernameVariable: 'GITHUB_USERNAME',
                passwordVariable: 'GITHUB_TOKEN'
            )
        ]) {
            sh '''
                echo "===================================="
                echo "Update Deployment File"
                echo "===================================="

                echo "Current directory:"
                pwd

                echo "Workspace contents:"
                ls -la

                echo "Checking manifest directory:"
                ls -la spring-boot-app-manifests/

                echo "Checking deployment file:"
                ls -l spring-boot-app-manifests/deployment.yml

                git config user.email "afthabvadassery@gmail.com"
                git config user.name "${GIT_USER_NAME}"

                echo "Updating Docker image..."

                sed -i "s|image: .*|image: afthab12/spring-boot-app:${BUILD_NUMBER}|g" spring-boot-app-manifests/deployment.yml

                echo "Deployment file after update:"
                cat spring-boot-app-manifests/deployment.yml

                git add spring-boot-app-manifests/deployment.yml

                git commit -m "Update spring boot image tag to ${BUILD_NUMBER} [skip ci]" || echo "No changes to commit"

                echo "Pushing changes to GitHub..."

                git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
            '''
        }
    }
}
